language: php
php:
- '5.5'

script: echo "We don't have tests yet :("

before_deploy:
- sh config.sh
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: IyzopXE2+0h48v9pSd/apxHzAfPDoy5UTxRcwPqXuTjiUTB1f5S5qL39ZsaSjI6IX/YUqdP3lovdZtMdrvstAKy5BUNQ1YQ9+oByD24OAMFFPa1WLlN8uMRx2wuKJSYryumVvfFXiuOYohf27d7xvQs+GOeKDdElr152mLqTQNUttP9vDn7juv/ftGXR/UDUx1cnozrIcPtXiS4xoddgGUsZ1ZGwm/8c0mzduUuIM5sbi1aXLE3JL6D71xQ8Ux61XjoXkLAJSBnlDZIRsRLXbaXbnP7He4XEG8X8x7/4TVBOyotSN1UzGvsm5vt7bhDzknT3i9itjki4Eoyoh7a6rdgpByrd2gETOrSMpOVblMwKf2kYSboA0a+svUMbUxROWgpXf5QGGMCqulcM0aQ+NyvszrAQgA3UZSfJLARMg1SGIpFxu/0NcwvndSkaaTRzHm4uv0Ae3XCKUg6WUtN4XD42lSpMXs/GbYgMr3XufsFzHdA6ytOOpbxgH0+agAP3JWYgEQPcCTpm+Hqkl936RK+TylV4oSAbrUzhZ8U4AhIvBnIFI6L0poyMn0ypVG6bJnrp63nd0YVtBlisCm74t9IH6HWoeZZvq3WSV3lN5CMNlijy42/uzQmSznoKdXt1IleQGkmwxWNQtF1dtOXY/QiE515AOxefFOq6yLckWk0=
  file: "plugin-transbank-onepay-virtuemart3-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-virtuemart-onepay
    tags: true
