language: php
php:
- '5.5'

script: echo "We don't have tests yet :("

before_deploy:
- sh config.sh
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: oPMgyMtiUDLm8FlsJdvF7PqvwFA64gI+g6h3BWTJ+hGtNEcl7j8c7XWwErADcaWpiPn2kBSG3YqogkbCFZTwJSrY0a6u4CziKoXp2ldM3aXdDZUwRZTsrz0tZhOjD80B3ALxEhVsS4MBrpM3XIkEk5/4HvywZ2r9WWooee7bMoqgRteQGmiSNeXIgZsmJx/yiL/h+hB6rxSQ7XcDoF8amZn2RiulTh0MLSwAmfVnUfO4sR5D9/LaU5hQYGnrlBCtpmxv62ceYtpVCplD4BDyN8EYB2Wmz3zpQkgXZgUa+ehzCH7htwTtO0F2looamnku22n8/TQpgZmSt9BQyXicRDz5fMxjBS66t21XJNSQlP0BgNA5Lb+UiLPezEKfD2SchtzrNvioXyXsE2qWYLN/t0bH4Tf0TlFScyOZxn+rmNaCZTc/PgwlwMd4RIFUw6oaZe3HkVQf6M6+9JwBeFTZBmYNEh/9bAEVl2OB8kD6z9T6Z4kXDaz94KoALgeYGE1ZexV0LX073nZKAQLdxMLFuBCJ8t/tgZ9u+neNtriz9oKLCd4W0chDaEZqPttc4p1wAJJE/sRM3BYXdmg7UoLYL1n6xYQ93qoP5hFBfTxQ3jdh+IywXTjxZAzxKPIkh9mvJ4f0NUHd3fjhOWZdG/YeV4R2MEDomWvlLsnUKzQWpCg=
  file: "plugin-transbank-onepay-virtuemart3-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-virtuemart-onepay
    tags: true
