#!/usr/bin/env bash
docker-compose up -d && \
echo "
========================================

      🌎 Web server: http://localhost/

      ⚙️ Admin: http://localhost/administrator/

            user: admin
            password: password

========================================"
